### ISSUE TITLE
Upgrade to `nan@2.x.x`

### ISSUE THREAD

**Issue by twolfson** [Shouqun/node-dbus#105]
When upgrading to `electron@0.31.0` we ran into an issue with respect to `dbus`. `0.31.0` is using `iojs@3.1.0` which seems to be unsupported by our current version of `nan`. Can we upgrade to `nan@2.x.x`?

I feel bad about not submitting a PR but I don't know C++ (and don't have time at the moment to learn it) -_-;;

**Comment by mkrufky** [comment]
Please lets do a minor version bump to 0.2.13 after merging this
