### ISSUE TITLE
Build failing after nan update

### ISSUE THREAD

**Issue by pcarranzav** [Shouqun/node-dbus#108]
We're using this module in [resin-io/resin-wifi-connect](https://github.com/resin-io/resin-wifi-connect), as it is a dependency of [Doodle3D/connman-api](https://github.com/Doodle3D/connman-api). It used to build fine, but after the recent version bump we are getting:
```
  CXX(target) Release/obj.target/dbus/src/object_handler.o
../src/signal.cc: In function ‘void Signal::DispatchSignal(v8::Handle<v8::Value>*)’:
../src/signal.cc:29:83: error: invalid conversion from ‘v8::Handle<v8::Value>*’ to ‘v8::Local<v8::Value>*’ [-fpermissive]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(handler), 6, info);
                                                                                   ^
```

See resin-io/resin-wifi-connect#21 - tried in 0.10 and 0.12 and neither of them works.

**Comment by mkrufky** [comment]
I tested my fix in PR #109 against v0.10.29 - can you test it also in v0.12.x (and v4 if possible)
