### ISSUE TITLE
Array of Strings should be marshalled with type 'as', currently is not.

### ISSUE THREAD

**Issue by jostrander** [Shouqun/node-dbus#120]
Sorry to be vague, but I'm not sure how to see the ASCII version of the type it currently is. 

Currently however I'm trying to work with the mpris spec, and it states that `xesam:artist` should be an "array of strings" or type `as`, which in JS is `["string one", "string two"]`, etc.

However this code: 
```javascript
{
    'mpris:artUrl': newSong.albumArt,
    'xesam:asText': (newSong.lyrics || ''),
    'xesam:title': newSong.title,
    'xesam:album': newSong.album,
    'xesam:artist': [newSong.artist], // particularly here.
};
```
is producing:
```
dict entry(
 string "xesam:artist"
 variant                      array [
       variant                         string "The Glitch Mob"
    ]
)
```
which has a variant type before string, instead of 
```
dict entry(
   string "xesam:artist"
   variant                      array [
         string "The Glitch Mob"
      ]
)
```
which is produced by players that are currently following spec. Is there something I can do JS side to force removal of the variant type before the string?

**Comment by mkrufky** [comment]
I was able to locate the offending block of code that is causing your problem.  Take a look at the function `GetSignatureFromV8Type` located in src/encoder.cc :
https://github.com/Shouqun/node-dbus/blob/master/src/encoder.cc#L28

This function analyzes the incoming `v8` type (from javascript) to determine what type to use for DBUS.  Since javascript (and in turn, `v8`) itself handles any type of array as an array of variant type, the function assumes any `v8` array to be an array of variant.

If you want to try a hack, you can replace 
```
if (value->IsArray()) {
			return const_cast<char*>(DBUS_TYPE_ARRAY_AS_STRING DBUS_TYPE_VARIANT_AS_STRING);
```
with
```
if (value->IsArray()) {
			return const_cast<char*>(DBUS_TYPE_ARRAY_AS_STRING DBUS_TYPE_STRING_AS_STRING);
```
...unfortunately, such a hack will force all `v8` arrays to be treated as an array of strings, and we don't want that in most cases.

If this hack works for you, perhaps the `GetSignatureFromV8Type` could be altered to recurse through the given array and return a specific array type if all items are of the same type... but, this can be expensive.

Can your software be modified to handle an array of variant string, instead?

**Comment by mkrufky** [comment]
...actually, walking the array shouldn't be too expensive - I'm working on a patch for testing right now, will post soon.

**Comment by mkrufky** [comment]
@jostrander please try https://github.com/mkrufky/node-dbus/commit/9bc73f4b61044274ab433f4a1ccf05b721ed118d  ...if it works for you, then we can try to merge it (assuming everybody is OK with this change)

**Comment by jostrander** [comment]
Awesome! I'll download it and give it a try and see how it goes!

**Comment by mkrufky** [comment]
I had to re-spin that branch to fix my own spelling error in a commit message.  You can find the fix in this branch:  https://github.com/mkrufky/node-dbus/tree/array-of-strings

**Comment by jostrander** [comment]
I tried it out, but it doesn't seem to have changed the output. I'm going to try and do a reduced test case because compiling it into the main project above takes way too much time to debug and test.

**Comment by mkrufky** [comment]
If it does end up working for you, we'll be more likely to want a more complete solution for all array item types...  this branch has a more complete experimental fix: https://github.com/mkrufky/node-dbus/tree/fix-arrays-of-same-item-type , including the following change: 

A javascript array is always handled as an array of variant.

This steps through an array to confirm that all elements are of the same type,
then produces a dbus structure accordingly, now supporting:

* array of boolean
* array of byte
* array of uint32
* array of int32
* array of double
* array of string

and defaulting to array of variant otherwise.

**Comment by jostrander** [comment]
Well I did a reduced test case and it works! Thank you!

**Comment by mkrufky** [comment]
Amazing!  I just happen to be re-reading this ticket the moment you posted that :-)  Which exact branch did you test?  If you have time, can you test the https://github.com/mkrufky/node-dbus/tree/fix-arrays-of-same-item-type branch?  If that works for you I will submit a pull request.

**Comment by jostrander** [comment]
I tested the last one you posted, only with string, but I can test the other types too real quick.

**Comment by mkrufky** [comment]
If you could test the other types and post results here that would be great.  Thanks for the testing. :-)

**Comment by jostrander** [comment]
Excuse my ignorance on the byte array, not sure how to do that. And Int might be broken?

```
var byteArray = new ArrayBuffer(16);
 
     player.metadata = {
         'mpris:trackid': player.objectPath('track/0'),
         'mpris:length': 60 * 1000 * 1000, // In microseconds
         'mpris:artUrl': 'http://www.adele.tv/images/facebook/adele.jpg',
         'xesam:title': 'Lolol',
         'xesam:album': '21',
         'xesam:artist': [ 'Adele' ],
         'stringTest': ['testOne', 'testTwo'],
         'booleanTest': [ true , false ],
         'byteTest': byteArray , 
         'uint32Test': [ 4294967295 , 4294967295 ],
         'int32Test': [ 1 , 2, 3 ], 
         'doubleTest': [ 1.1, 2.1, 3.1, 4.1 ],
    }; 
```

```
array [
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "mpris:trackid"
                  variant                      string "/org/node/mediaplayer/nodejs/track/0"
               )
               dict entry(
                  string "mpris:length"
                  variant                      uint32 60000000
               )
               dict entry(
                  string "mpris:artUrl"
                  variant                      string "http://www.adele.tv/images/facebook/adele.jpg"
               )
               dict entry(
                  string "xesam:title"
                  variant                      string "Lolol"
               )
               dict entry(
                  string "xesam:album"
                  variant                      string "21"
               )
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        string "Adele"
                     ]
               )
               dict entry(
                  string "stringTest"
                  variant                      array [
                        string "testOne"
                        string "testTwo"
                     ]
               )
               dict entry(
                  string "booleanTest"
                  variant                      array [
                        boolean true
                        boolean false
                     ]
               )
               dict entry(
                  string "byteTest"
                  variant                      array [
                     ]
               )
               dict entry(
                  string "uint32Test"
                  variant                      array [
                        uint32 4294967295
                        uint32 4294967295
                     ]
               )
               dict entry(
                  string "int32Test"
                  variant                      array of bytes [
                        01 02 03
                     ]
               )
               dict entry(
                  string "doubleTest"
                  variant                      array [
                        double 1.1
                        double 2.1
                        double 3.1
                        double 4.1
                     ]
               )
            ]
      )
   ]
```

**Comment by mkrufky** [comment]
looks like the ints in the int32Test were passed as bytes.  if you explicitly pass them in as integers, or use negative values, or values higher than 256, im sure they will be passed as int32 correctly.   It looks like this is working correctly, but this behavior of int32 should be noted somehow...

**Comment by mkrufky** [comment]
Can you try again with:

'int32Test': [ parseInt(1) , parseInt(2), parseInt(3) ],

**Comment by jostrander** [comment]
That did it..
```
               dict entry(
                  string "int32Test"
                  variant                      array [
                        int32 -1
                        int32 2
                        int32 3
                        int32 300
                     ]
               )

	    'int32Test': [ -1 , parseInt(2), parseInt(3), 300 ],

```

**Comment by mkrufky** [comment]
pushing a patch to fix this now...

**Comment by mkrufky** [comment]
@jostrander I believe I fixed that issue... the https://github.com/mkrufky/node-dbus/tree/fix-arrays-of-same-item-type should work fine now for all of the above tests...  Please confirm.  Thanks again for your testing.

**Comment by mkrufky** [comment]
actually, I think the same issue will be present with [ 01, 02, 03 ] ... i'm pushing up one more patch...

**Comment by mkrufky** [comment]
I think this is "good enough" ... it reveals that if you simply pass an 0 <= integer < 256, the dbus message will be treated as a byte, likewise, a series of integers 0 <= x < 256 will be treated as a series of bytes.  The moment one of them is seen as NOT a byte, then they will be treated as int32 or uint32, accordingly.  That's just my opinion.  I agree that it can be confusing and should be documented somehow.

**Comment by jostrander** [comment]
I agree, everything else is working flawlessly from what I can tell.

**Comment by mkrufky** [comment]
now also supporting `array of array` (variant) and `array of object` ...  please feel free to comment on PR #121

**Comment by jostrander** [comment]
Above and beyond! Thank you for the quick work on this!
