### ISSUE TITLE
Marshall to int64?

### ISSUE THREAD

**Issue by jostrander** [Shouqun/node-dbus#126]
I realize that v8 technically speaking does not handle int64, so if this is impossible please feel free to close. Currently however, passing large numbers to the marshaller it either declares it a double or a uint32. Unfortunately (for our project) the spec for org.mpris.MediaPlayer2 states that the timestamp needs to be an int64. Would there be any way to force the marshaller to output int64 type?

**Comment by mkrufky** [comment]
for kicks, try out this branch:  https://github.com/mkrufky/node-dbus/tree/marshall-to-int64

**Comment by jostrander** [comment]
Your branch marshalls any positive integer larger than a uint32 into a uint64, and any negative integer larger than a uint32 into an int64 from what I can tell. 

Unfortunately what I realize I failed to specify, was that the number I'm providing the marshaller is small enough to fit into a uint32 in most cases, which is why I figured it wouldn't be possible to force int64 instead of uint32.

**Comment by jostrander** [comment]
Just for sng, my use case is a song length in micro seconds (185000000μs in my test case), which marshalls fine into a uint32 as it should. Times like this I wish it was possible to type hint in JavaScript itself.

**Comment by mkrufky** [comment]
This sounds better than the current state, which doesn't support 64bit integers at all, although it doesn't seem to solve your problem since your integers actually fit in a uint32.  For sure, we would rather see these larger integers marshaled as UINT64 / INT64 rather than DOUBLE, so it might be a good idea to merge this in some form or another.  ...but I think you'll need finer grained control of the marshaling.

**Comment by jostrander** [comment]
Yep I agree entirely, if I was actually working with 64 bit integers this would solve it no problem.

**Comment by mkrufky** [comment]
What if you used v8 to create a Local<Integer> (a int64_t internally) and assign the 32bit int value to that value, then pass that value by reference into the marshaller?

**Comment by jostrander** [comment]
Do you have example code? I don't quite comprehend, would that be JS only, or a mix of native/JS?

**Comment by mkrufky** [comment]
It would be a hacky mix of native + JS ...  I'll throw something together and test it myself when I have some more time...

**Comment by jostrander** [comment]
I think I see what you're saying, basically pass a value into a native module that will typecast it into a 64bit integer and return it to JS to be sent back to node-dbus so that it will interoperate it correctly for my needs?

**Comment by mkrufky** [comment]
Yes, that is what I was suggesting, but I don't know for sure if it will work.  I think it's worth a try...

**Comment by jostrander** [comment]
I tried this on my own, and no matter what I do I end up with a uint32 or double, as there is no official way to get a 64 bit back into JS, however I'm not very good with c++, I just used one of the example native modules and tried getting it to return a 64 bit integer with a number that was passed in.

https://gist.github.com/jostrander/a19debe43381f45b9fab8f4a196a21a4

Setting the return value to `value` threw compile errors as it's not expecting an int64_t.

**Comment by mkrufky** [comment]
What if you replace:
```
  int64_t value = args[0]->IntegerValue();
  Local<Integer> num = Integer::New(isolate, value);
  args.GetReturnValue().Set(num);
```
with:
```
  args.GetReturnValue().Set(value->ToInteger());
```

I have a feeling it won't work, but this is specifically what I had in mind, forcing the actual Local<Integer> handle to be returned by reference

**Comment by mkrufky** [comment]
If you wrap the `v8::Local<Integer>` in a `v8::Persistent`, you can pass that `v8::Persistent` by reference to `args.GetReturnValue().Set()`  If anything is going to work, it's that.

**Comment by jostrander** [comment]
```

**Comment by mkrufky** [comment]
Your comment above doesn't show up for some reason...  Anyway, for the `v8::Persistent` path, maybe something like this:
```
Local<Integer> num = args[0]->ToInteger();
Persistent n;
n.reset(isolate, num)
args.GetReturnValue().Set(n);
```

**Comment by jostrander** [comment]
My mistake, I hit enter too soon after doing \```

Anyway, that threw this:
```
../64bitint.cc: In function ‘void return64bit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../64bitint.cc:18:14: error: missing template arguments before ‘n’
   Persistent n;
              ^
../64bitint.cc:18:14: error: expected ‘;’ before ‘n’
../64bitint.cc:19:3: error: ‘n’ was not declared in this scope
   n.reset(isolate, num);
```

**Comment by mkrufky** [comment]
(edited) that should have been a `Persistent<Integer>`

**Comment by jostrander** [comment]
Integer, Value, Number, all fail at n.reset()

```
../64bitint.cc: In function ‘void return64bit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../64bitint.cc:19:5: error: ‘class v8::Persistent<v8::Integer>’ has no member named ‘reset’
   n.reset(isolate, num);```

This is beyond the scope of my understanding of v8 and c++, I understand the error, just not what it's expecting or what it does.

**Comment by mkrufky** [comment]
My bad.  It's a capitol `R` in `Reset()`

**Comment by jostrander** [comment]
Still looks to be double precision, though I'm only verifying by doing a console.log on a number one less than the 64bit max. Should I try marshalling the result and see what it comes up with?

**Comment by mkrufky** [comment]
trying it is the only way to know for sure.....   Also, can you show me the code snippet that you use to send data to the marshaller?

**Comment by jostrander** [comment]
Using https://github.com/emersion/node-mpris and the example/player.js file to do the marshalling. and in this case I just required in the 64bit module from above and used its result in the length line instead of the  `60 * 1000 * 1000`. Still returned a uint32 though.

**Comment by mkrufky** [comment]
Oh well... it was worth a try.  The only thing I can imagine would help would be to add a new interface to the node-dbus that would allow an optional signature to be passed with any data to be marshalled, which would end up being passed into:
```
bool EncodeObject(Local<Value> value, DBusMessageIter *iter, const char *signature);
```

**Comment by jostrander** [comment]
I'm looking at the source of emitSignal, and I notice that mpris-service is passing a blank array into the signatures area of emitSignal:
https://github.com/Shouqun/node-dbus/blob/master/src/signal.cc#L68
and
https://github.com/emersion/mpris-service/blob/master/index.js#L79

Is that where I could possibly pass in the signature?

**Comment by mkrufky** [comment]
aha!  Yes, that's exactly what you need.  This should solve your problem.  Figuring out the proper signature might be interesting though... I suggest adding some printf's to encoder.cc after line 414 to view the `var_sig` to see what the signature currently looks like.

**Comment by jostrander** [comment]
I think it's already figured out inside of 
https://github.com/Shouqun/node-dbus/blob/535297848e72fc7bf7c74fc20c2cbaf74e97e15b/lib/service_interface.js#L166-L186

but for some reason mpris-service didn't implement lines 180-183 and instead chose to pass a blank array. If I can filter that I should be able to specify the ascii code for that if it's present, correct? (What is the ascii code for int64?)

**Comment by jostrander** [comment]
Also, derp, the encoder already has a case for INT64:

https://github.com/Shouqun/node-dbus/blob/master/src/encoder.cc#L198

**Comment by mkrufky** [comment]
Yes, `EncodeObject()` already supports encodinng INT64 and UINT64 when a signature is manually specified.  You need my patch, however, to get the marshaler to autodetect INT64 / UINT64 in `GetSignatureFromV8Type()`  I just sent a PR for supporting INT64 for numbers that don't fit in a UINT32... #127

**Comment by mkrufky** [comment]
the ascii code for int64 is designated by the macro `DBUS_TYPE_INT64`

**Comment by jostrander** [comment]
I would still have to use the ASCII code of `x` in the signature array passed by emitSignal correct?

**Comment by mkrufky** [comment]
I'm not sure what you mean, exactly, but you would need to use the same exact signature array, but just replace the `DBUS_TYPE_INT32` char with a `DBUS_TYPE_INT64` char

**Comment by mkrufky** [comment]
I found a pretty big bug in that branch that would marshal it as a double instead int64, fixed now...

**Comment by jostrander** [comment]
I think I've found the majority of my issue, and I'm not sure if it's even fixable. So in the [MPRIS spec](https://specifications.freedesktop.org/mpris-spec/latest/#The-PropertiesChanged-signal): "The MPRIS uses the org.freedesktop.DBus.Properties.PropertiesChanged signal to notify clients of changes in the media player state." 

So you can see that being registered [here](https://github.com/emersion/mpris-service/blob/master/index.js#L41) with the proper [types and names](https://dbus.freedesktop.org/doc/dbus-specification.html) (ctrl+f for PropertiesChanged) being registered for that signal. It states the signal needs to be

```
    org.freedesktop.DBus.Properties.PropertiesChanged (STRING interface_name,
                                     DICT<STRING,VARIANT> changed_properties,
                                     ARRAY<STRING> invalidated_properties);
```

Further down in the mpris file, we have [this signal being emitted](https://github.com/emersion/mpris-service/blob/master/index.js#L79) which spits out exactly what is expected, the interface name, the properties changed, and an empty array of invalidated properties. 

The issue is that with the properties changed, there's no way to manually set the types. The data is passed through [here](https://github.com/Shouqun/node-dbus/blob/master/lib/service_interface.js#L185) to this native method [here](https://github.com/Shouqun/node-dbus/blob/535297848e72fc7bf7c74fc20c2cbaf74e97e15b/src/signal.cc#L43). Then everything is auto encoded down on line 94 of that method. There is a list of signatures passed in, but it's the signature for the signal, not for the individual properties. I believe I could try to alter the properties_changed signal to output the full signature for the properties that are going ot be changed, eg. from `a{sv}` to `a{sa{ss}a{sx}}` etc, but that would require manually figuring out the type and setting it inside of the types array before every emit, which I'm not sure is the correct way to go about doing that, or if it would even work.

**Comment by mkrufky** [comment]
if you want to fork node-dbus (looks like your project already has a fork), you can add some kind of hack-toggle api to trigger a "try as an INT64 first" option, which would change `GetSignatureFromV8Type()` in encoder.cc to try `IsInt64()` before trying `IsInt32()`

It's not pretty, and of course it would be much better to have an upstreamable solution, but a hack like that should get you by in the meanwhile.

Ideally you would enable the hack before sending this kind of message, then disable it immediately afterwards.  Probably better off to use a mutex or something javascripty

**Comment by jostrander** [comment]
A version that only uses int64 and double might work, as I don't think there is anything in the spec for anything other than those. Obviously it'd be highly specific to our project at that point, but it would work. Thank you for all the help with troubleshooting!
