### ISSUE TITLE
Update dependancies/add to install list?

### ISSUE THREAD

**Issue by Quacky2200** [Shouqun/node-dbus#128]
I was able to find how to get the package installed but I had to install expat dev tools (libexpat1-dev on Ubuntu 14.04.04), could this be added to the dependencies list as it's easy to forget, I've already forgotten once when installing this on another machine and so I made this issue/request.

**Comment by cruxdyno** [comment]
Same on ubuntu 16.04.01

**Comment by Shouqun** [comment]
fixed by using builtin libexpat
