### ISSUE TITLE
Question: How to properly close a bus

### ISSUE THREAD

**Issue by lukas-zech-software** [Shouqun/node-dbus#133]
We are using **dbus** to query **connman** network manager.

As our application does not execute this query very often, we want to close the connection after we received the data over the bus.

After studying the docs and the code, we did not find any clean solution to close the bus after usage.

Is this possible? If so how?

**Comment by Juul** [comment]
I'm having the same issue. Looking through the code it appears you cannot close it. The closest thing is bus.reconnect() which doesn't even work correctly and gives this warning:

```
Applications must not close shared connections - see dbus_connection_close() docs. This is a bug in the application.
```
