### ISSUE TITLE
How to add property type 'as' or 'a{qv}'?

### ISSUE THREAD

**Issue by sskcorea** [Shouqun/node-dbus#190]
Hi 

How can I add properties which type is 'as' or 'a{qv}' ? 
`// Is this right way to set property?
iface1.addProperty('Type', {

	type: 'as',
	getter: function(cb) {
	}
});`

I found this code in utils.js and I doubt node-dbus doesn't support those kind of types.
`var Signature = function(type) { 

	if (type == 'Auto') {
		return 'v';
	} else if (type === String) {
		return 's';highly 
	} else if (type === Number) {
		return 'd';
	} else if (type === Boolean) {
		return 'b';
	} else if (type === Array) {
		return 'av';
	} else if (type === Object) {
		return 'a{sv}';
	} 
	return 'v';
};`

Any comments and possible ideas would be highly appreciated.

Thanks

**Comment by FliiFe** [comment]
I believe what you want is 
```javascript
type: {
    type: 'as'
}
```
instead of just `type: 'as'`

**Comment by sskcorea** [comment]
I confirmed. Thanks FliiFe!
