### ISSUE TITLE
Fail to marshal method with array of bytes param

### ISSUE THREAD

**Issue by dtymon** [Shouqun/node-dbus#20]
Hi Shouqun,

I have a method that has an array of bytes (type 'ay') as one of the args and node-dbus fails to marshal this type. I had a look into it and it appears to be a simple logic problem in dbus.cc. Also, this bug highlighted another issue where a double free was being done. This patch appears to fix both issues:

https://gist.github.com/3052072#file_node_dbus_array.patch

**Comment by benfrancis** [comment]
I think I'm having a similar/the same issue in #228.

@dtymon Can I ask how you were creating the byte array in Node.js?

@Shouqun Was this fix ever applied?

Thank you
