### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by stramel** [Shouqun/node-dbus#87]
There seems to be issues with compiling against newer versions of node. Would you mind looking at upgrading it? 0.11 would be nice :+1:

**Comment by akras14** [comment]
What kind of errors are you getting? I was able to resolve mine by installing the following missing dependencies on Ubuntu. I am on Node v0.10.33.

``` bash
sudo apt-get install node-gyp
sudo apt-get install libdbus-1-dev
sudo apt-get install libexpat1-dev
```

**Comment by akras14** [comment]
Just realized that their NPM page already lists the needed dependencies... https://www.npmjs.com/package/node-dbus

May be the README file can be updated.

**Comment by akras14** [comment]
I've update a README file with my findings, and made a pull request #88. Hopefully, this will be helpful to others.

**Comment by stramel** [comment]
@akras14 Thanks, I don't remember my exact issue but found https://github.com/sidorares/node-dbus
which seemed to solve the issue. I will attempt with your suggestions  when I find time. Thanks!

**Comment by hoigo** [comment]
Does it compile under Node 0.12.0? I've tried it, but when I run the example service.js file I got an error with an undefined symbol.

**Comment by cfsghost** [comment]
node-dbus is working well on Node.js 0.12 and io.js now. please check it. :-)

**Comment by hoigo** [comment]
thanks. I'm gonna check it.

**Comment by hoigo** [comment]
When running the examples (without X11) I got the following error at the callback of getting the interface: "No introspectable". The interface object is undefined.

Do you have any hints?
